services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dip_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}

volumes:
  db_data:
