spring.application.name=attendance
server.port=8080

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/dip}
spring.datasource.url=jdbc:postgresql://localhost:5432/dip
spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=${POSTGRES_USER:dip}
spring.datasource.username=dip
#spring.datasource.password=${POSTGRES_PASSWORD:dip123}
spring.datasource.password=dip

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

security.jwt.secret=${SECURITY_JWT_SECRET:}
